# Actuate R8 / ProGuard rules (release builds)

# --- kotlinx.serialization ---
# Keep serializers generated by the kotlinx.serialization plugin for all @Serializable models.
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.AnnotationsKt

-keepclassmembers class kotlinx.serialization.json.** {
    *** Companion;
}
-keepclasseswithmembers class kotlinx.serialization.json.** {
    kotlinx.serialization.KSerializer serializer(...);
}

# Keep @Serializable classes and their generated companion serializers.
-keep,includedescriptorclasses class com.actuate.**$$serializer { *; }
-keepclassmembers class com.actuate.** {
    *** Companion;
}
-keepclasseswithmembers class com.actuate.** {
    kotlinx.serialization.KSerializer serializer(...);
}

# --- Retrofit/OkHttp are R8-friendly by default; nothing extra needed ---

# --- Compose ---
# Compose ships consumer rules; keep animations/assets intact.
-dontwarn androidx.compose.**