# Actuate R8 / ProGuard rules (release builds)
#
# Design intent (see todo 1 of the bold-overhaul plan):
#   * Obfuscation is ENABLED. We never use `-dontobfuscate`.
#   * Only the pieces that are reached through reflection / JNI / serialization
#     contracts are preserved. Application code is shrunk and obfuscated normally.

-keepattributes Signature, Exceptions, *Annotation*, InnerClasses, EnclosingMethod
-keepattributes RuntimeVisibleAnnotations, RuntimeVisibleParameterAnnotations

# Kotlin metadata is read by kotlin-reflect and by some libraries at runtime.
-keep class kotlin.Metadata { *; }
-dontwarn kotlin.**

# --- kotlinx.serialization ---
# Keep serializers generated by the kotlinx.serialization plugin for all @Serializable models.
-dontnote kotlinx.serialization.**

-keepclassmembers class kotlinx.serialization.json.** {
    *** Companion;
}
-keepclasseswithmembers class kotlinx.serialization.json.** {
    kotlinx.serialization.KSerializer serializer(...);
}

# Keep @Serializable classes, their generated serializers and companions.
-keep,includedescriptorclasses class com.actuate.**$$serializer { *; }
-keepclassmembers class com.actuate.** {
    *** Companion;
}
-keepclasseswithmembers class com.actuate.** {
    kotlinx.serialization.KSerializer serializer(...);
}

# Persistence contracts (DataStore / local action store) round-trip JSON and must
# survive shrinking by name.
-keep class com.actuate.data.storage.** { *; }
-keep class com.actuate.data.store.** { *; }
-keepclassmembers class com.actuate.data.storage.** { *; }
-keepclassmembers class com.actuate.data.store.** { *; }

# --- Retrofit/OkHttp are R8-friendly by default; nothing extra needed ---
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn javax.annotation.**

# --- Compose ---
# Compose ships consumer rules; keep animations/assets intact.
-dontwarn androidx.compose.**

# --- Native & Whisper.cpp JNI boundary ---
-keepclasseswithmembernames class * {
    native <methods>;
}
-keep class com.actuate.data.speech.whisper.WhisperLib {
    native <methods>;
    *;
}
-keep class com.actuate.data.speech.whisper.** { *; }
-keep class com.actuate.data.speech.audio.** { *; }
-dontwarn com.actuate.data.speech.whisper.**

# --- RevenueCat ---
# The SDK ships consumer rules; these are belt-and-braces keeps for the models
# it materialises reflectively.
-keep class com.revenuecat.purchases.** { *; }
-keep class com.revenuecat.purchases.models.** { *; }
-dontwarn com.revenuecat.purchases.**

# --- Koin ---
-keep class io.insert.koin.** { *; }
-keep class org.koin.** { *; }
-dontwarn io.insert.koin.**
-dontwarn org.koin.**

# --- ViewModels & Architecture Components ---
-keep class * extends androidx.lifecycle.ViewModel {
    <init>(...);
}
-keep class * extends androidx.lifecycle.AndroidViewModel {
    <init>(...);
}

# --- Activity / Application entry points referenced from the manifest ---
-keep class com.actuate.app.MainActivity { *; }
-keep class com.actuate.app.ActuateApplication { *; }
-keep class com.actuate.data.reminders.ReminderReceiver { *; }
